package com.patbaumgartner.habithooks.init;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import static org.assertj.core.api.Assertions.assertThat;

class ProjectInitializerTest {

    @TempDir
    Path tempDir;

    @Test
    void dryRunDoesNotWriteAnyFiles() {
        Output output = run(true, false);

        assertThat(output.text()).contains("[dry-run]");
        assertThat(Files.exists(tempDir.resolve(".habit-hooks.yaml"))).isFalse();
        assertThat(Files.exists(tempDir.resolve("checkstyle.xml"))).isFalse();
        assertThat(output.text()).contains("write AGENTS.md");
    }

    @Test
    void writesScaffoldFilesWhenAbsent() throws IOException {
        Output output = run(false, false);

        assertThat(output.text()).contains("initialized");
        assertThat(output.text()).contains("habit-hooks --all");
        assertThat(Files.exists(tempDir.resolve("checkstyle.xml"))).isTrue();
        assertThat(Files.exists(tempDir.resolve("pmd-ruleset.xml"))).isTrue();
        assertThat(Files.exists(tempDir.resolve(".habit-hooks.yaml"))).isTrue();
        assertThat(Files.exists(tempDir.resolve(".habit-hooks-baseline.json"))).isTrue();
        assertThat(Files.exists(tempDir.resolve("AGENTS.md"))).isTrue();
        assertThat(Files.exists(tempDir.resolve("habit-hooks-maven-snippets.xml"))).isFalse();
        assertThat(Files.readString(tempDir.resolve(".habit-hooks.yaml"))).contains("spotbugs:", "spring-javaformat:");
        assertThat(Files.readString(tempDir.resolve("AGENTS.md"))).contains("habit-hooks --all",
                "habit-hooks tasks --format json --no-fail", "changed-file loop", "Conventional Commits");
        assertThat(Files.readString(tempDir.resolve("checkstyle.xml"))).contains("FileTabCharacter",
                "EmptyLineSeparator", "value=\"20\"", "value=\"4\"", "value=\"6\"");
    }

    @Test
    void springBootModeEnablesFullAnalyzerSurface() throws IOException {
        Files.createDirectories(tempDir.resolve("src/test/java"));

        Output output = run(false, false, false, true);
        String config = Files.readString(tempDir.resolve(".habit-hooks.yaml"));
        String agents = Files.readString(tempDir.resolve("AGENTS.md"));

        assertThat(output.text()).contains("Spring Boot analyzers were enabled");
        assertThat(config).contains("generated by habit-hooks init --spring-boot", "onlyChangedFiles: false",
                "taikai:\n    enabled: true", "spotbugs:\n    enabled: true", "jspecify:\n    enabled: true",
                "-Phabit-hooks-analyzers", "-Phabit-hooks-errorprone", "strict validation profile",
                "-DautoUpdate=false");
        assertThat(agents).contains("Spring Boot Agent Guide", "Expected Analyzer Surface", "tight local loop",
                "Conventional Commits");
        assertThat(Files.exists(tempDir.resolve("habit-hooks-maven-snippets.xml"))).isTrue();
        assertThat(Files.exists(tempDir.resolve("src/test/java/ArchitectureTest.java"))).isTrue();
    }

    @Test
    void mavenSnippetsAreOptIn() throws IOException {
        run(false, false, true);

        Path snippets = tempDir.resolve("habit-hooks-maven-snippets.xml");
        assertThat(Files.exists(snippets)).isTrue();
        String content = Files.readString(snippets);
        assertThat(content).contains("spotbugs-maven-plugin");
        assertThat(content).contains("jacoco-maven-plugin");
        assertThat(content).contains("org.jspecify");
        assertThat(content).contains("com.enofex");
        assertThat(content).contains("habit-hooks-analyzers", "habit-hooks-errorprone", "mutation-test");
    }

    @Test
    void skipsFilesThatAlreadyExist() throws IOException {
        Files.writeString(tempDir.resolve("checkstyle.xml"), "<module/>");
        Files.writeString(tempDir.resolve("AGENTS.md"), "existing guide");

        Output output = run(false, false);

        assertThat(output.text()).contains("skip  checkstyle.xml (already exists)");
        assertThat(output.text()).contains("skip  AGENTS.md (already exists)");
        assertThat(Files.readString(tempDir.resolve("checkstyle.xml"))).isEqualTo("<module/>");
        assertThat(Files.readString(tempDir.resolve("AGENTS.md"))).isEqualTo("existing guide");
    }

    @Test
    void taikaiScaffoldsArchitectureTestWhenTestDirExists() throws IOException {
        Files.createDirectories(tempDir.resolve("src/test/java"));

        Output output = run(false, true);
        String architectureTest = Files.readString(tempDir.resolve("src/test/java/ArchitectureTest.java"));

        assertThat(output.text()).contains("Taikai tests require the com.enofex:taikai test dependency");
        assertThat(Files.exists(tempDir.resolve("src/test/java/ArchitectureTest.java"))).isTrue();
        assertThat(architectureTest).contains("\tprivate static final String NAMESPACE");
        assertThat(architectureTest).contains("private static Customizer<SpringConfigurer> springBootRules()",
                ".noAutowiredFields()", ".transactional(transactionalRules())",
                "private static Customizer<TestConfigurer> testRules()",
                ".methodsShouldContainAssertionsOrVerifications()", "org.slf4j.Logger");
        assertThat(architectureTest).doesNotContain("com.enofex.taikai.java.logging");
        assertThat(architectureTest).contains("// change this").doesNotContain("←");
    }

    @Test
    void taikaiIsSkippedWhenNoTestDirectory() {
        Output output = run(false, true);

        assertThat(output.text()).contains("no src/test/java found");
        assertThat(Files.exists(tempDir.resolve("src/test/java/ArchitectureTest.java"))).isFalse();
    }

    @Test
    void agentsOnlyWritesOnlyAgentsFile() {
        ByteArrayOutputStream buffer = new ByteArrayOutputStream();
        PrintStream out = new PrintStream(buffer, true, StandardCharsets.UTF_8);
        ProjectInitializer.Options options = new ProjectInitializer.Options(false, false, false, false, true);
        new ProjectInitializer(tempDir, options, out).initialize();

        assertThat(Files.exists(tempDir.resolve("AGENTS.md"))).isTrue();
        assertThat(Files.exists(tempDir.resolve("checkstyle.xml"))).isFalse();
        assertThat(Files.exists(tempDir.resolve(".habit-hooks.yaml"))).isFalse();
        assertThat(buffer.toString(StandardCharsets.UTF_8)).contains("AGENTS.md scaffolded");
    }

    private Output run(boolean dryRun, boolean taikai) {
        return run(dryRun, taikai, false);
    }

    private Output run(boolean dryRun, boolean taikai, boolean mavenSnippets) {
        return run(dryRun, taikai, mavenSnippets, false);
    }

    private Output run(boolean dryRun, boolean taikai, boolean mavenSnippets, boolean springBoot) {
        ByteArrayOutputStream buffer = new ByteArrayOutputStream();
        PrintStream out = new PrintStream(buffer, true, StandardCharsets.UTF_8);
        ProjectInitializer.Options options = new ProjectInitializer.Options(dryRun, taikai, mavenSnippets, springBoot,
                false);
        new ProjectInitializer(tempDir, options, out).initialize();
        return new Output(buffer.toString(StandardCharsets.UTF_8));
    }

    private record Output(String text) {
    }

}
